### ISSUE TITLE
Script errors

### ISSUE THREAD

**Issue by MMRHC** [itflow-org/itflow-api-powershell#5]
Getting the following error.  Any help/insight into what is going wrong?  Thanks.

API connection error. Aborting...
Invoke-RestMethod : Invalid URI: The hostname could not be parsed.
At C:\ProgramData\TacticalRMM\3173080032.ps1:112 char:11
+ $exists = Invoke-RestMethod -Method GET -Uri $uri_read
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], UriFormatException
    + FullyQualifiedErrorId : System.UriFormatException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by wrongecho** [comment]
Hey @MMRHC 

You'll probably be better off posting on the Forum than here: https://forum.itflow.org/t/support

Generally this is an issue with the parameters you've set in TRMM. Very similar queries here: https://forum.itflow.org/d/873-api-key-is-invalid-or-has-expired-trying-to-sync-with-tactical-rmm
